ignore_hosts: 
  - 'accounts.google.com'
  - 'amazonaws.com'
  - 'awsstatic.com'
  - 'bat.bing.com'
  - 'bootstrapcdn.com'
  - 'cdnjs.cloudflare.com'
  - 'clients2.google.com'
  - 'code.jquery.com'
  - 'doubleclick.net'
  - 'facebook.com'
  - 'fontawesome.com'
  - 'gmail.com'
  - 'google-analytics.com'
  - 'google.com'
  - 'googleapis.com'
  - 'googlesyndication.com'
  - 'googletagmanager.com'
  - 'googleusercontent.com'
  - 'gstatic.com'
  - 'gvt1.com'
  - 'jsdelivr.net'
  - 'maxcdn.com'
  - 'use.typekit.net'
  - 'www.google.com'
  - 'yandex.com'
  - 'yandex.ru'
  - 'youtube.com'
  - 'typekit.net'
  - 'connect.facebook.net'
  - 'analytics.yahoo.com'
  - 's.yimg.com'
  - 'pushnami.com'
  - 'hotjar.com'
  - 'googleadservices.com'
  - 'cloudinary.com'
  - 'img.emlasts.com'
  - 'atdmt.com'