ignore_hosts: 
  - '^(.+\.)?google\.com:443$'
  - '^(.+\.)?googleapis\.com:443$'
  - '^(.+\.)?gstatic\.com:443$'
  - '^(.+\.)?doubleclick\.net:443$'
  - '^(.+\.)?google-analytics\.com:443$'
  - '^(.+\.)?googleusercontent\.com:443$'
  - '^(.+\.)?jsdelivr\.net:443$'
  - '^(.+\.)?cdnjs.cloudfoare\.com:443$'
  - '^(.+\.)?fontawesome\.com:443$'
  - '^(.+\.)?maxcdn.bootstrapcdn.com\.com:443$'
  - '^(.+\.)?use.typekit\.net:443$'
  - '^(.+\.)?gvt1\.com'