ignore_hosts: 
  - '^(.+\.)?google\.com:443$'
  - '^(.+\.)?google\.com:80$'
  - '^(.+\.)?googleapis\.com:443$'
  - '^(.+\.)?googleapis\.com:80$'
  - '^(.+\.)?gstatic\.com:80$'
  - '^(.+\.)?gstatic\.com:443$'
  - '^(.+\.)?doubleclick\.net:80$'
  - '^(.+\.)?doubleclick\.net:443$'
  - '^(.+\.)?google-analytics\.com:80$'
  - '^(.+\.)?google-analytics\.com:443$'
  - '^(.+\.)?googleusercontent\.com:80$'
  - '^(.+\.)?googleusercontent\.com:443$'
  - '^(.+\.)?jsdelivr\.net:80$'
  - '^(.+\.)?jsdelivr\.net:443$'
  - '^(.+\.)?cdnjs.cloudflare\.com:80$'
  - '^(.+\.)?cdnjs.cloudflare\.com:443$'
  - '^(.+\.)?fontawesome\.com:80$'
  - '^(.+\.)?fontawesome\.com:443$'
  - '^(.+\.)?bootstrapcdn\.com:80$'
  - '^(.+\.)?bootstrapcdn\.com:443$'
  - '^(.+\.)?use.typekit\.net:80$'
  - '^(.+\.)?use.typekit\.net:443$'
  - '^(.+\.)?gvt1\.com:80$'
  - '^(.+\.)?gvt1\.com:443$'
  - '^(.+\.)?googlesyndication.com:80$'
  - '^(.+\.)?googlesyndication.com:443$'