local focus = require('config.windows.focus')
local manager = require('config.windows.manager')
local settings = require('config.windows.settings')
local helpers = require('config.windows.helpers')

local logger = require('config.windows.logger')

hs.hotkey.bind({ "ctrl", "cmd" }, "h", function()
  focus.focusWest()
end)
hs.hotkey.bind({ "ctrl", "cmd" }, "l", function()
  focus.focusEast()
end)

hs.hotkey.bind({ "shift", "cmd" }, "h", function()
  manager.moveWindowWest()
end)
hs.hotkey.bind({ "shift", "cmd" }, "l", function()
  manager.moveWindowEast()
end)
hs.hotkey.bind({ "shift", "cmd" }, "space", function()
  manager.toggleFill()
end)

hs.hotkey.bind({ "shift", "alt" }, "space", function()
  manager.fillAllWindows()
end)

hs.hotkey.bind({}, "f19", function()
  focus.toggleFocus()
end)
