#!/bin/zsh
# Focus the tab currently playing audio in Zen Browser

BT="/Users/kevin/.local/bin/bt"

tab_line=$($BT query +audible | head -1)

if [[ -n "$tab_line" ]]; then
  tab_id=$(echo "$tab_line" | awk '{print $1}')
  $BT activate "$tab_id"
  open -a "Zen Browser"
else
  echo "No audible tabs found" >&2
  exit 1
fi
