ignore_hosts:
  - 'accounts.google.com'
  - 'protonmail.com'
  - 'amazonaws.com'
  - 'awsstatic.com'
  - 'bat.bing.com'
  - 'bootstrapcdn.com'
  - 'cdnjs.cloudflare.com'
  - 'clients2.google.com'
  - 'code.jquery.com'
  - 'doubleclick.net'
  - 'fontawesome.com'
  - 'gmail.com'
  - 'google-analytics.com'
  - 'google.com'
  - 'googleapis.com'
  - 'googlesyndication.com'
  - 'googletagmanager.com'
  - 'googleusercontent.com'
  - 'gstatic.com'
  - 'gvt1.com'
  - 'jsdelivr.net'
  - 'maxcdn.com'
  - 'typekit.net'
  - 'www.google.com'
  - 'yandex.com'
  - 'yandex.ru'
  - 'youtube.com'
  - 'typekit.net'
  - 'facebook.com'
  - 'facebook.net'
  - 'analytics.yahoo.com'
  - 'yimg.com'
  - 'pushnami.com'
  - 'hotjar.com'
  - 'googleadservices.com'
  - 'cloudinary.com'
  - 'emlasts.com'
  - 'atdmt.com'
  - 'pingdom.com'
  - 'pixel.ad'
  - 'unpkg.com'
  - 'i.ytimg.com'
  - 'cdn.ampproject.org'
  - 'cdn.pushcrew.com'
  - 'rs.fullstory.com'
  - 'platform.twitter.com'
  - 'syndication.twitter.com'
