require 'plugins'
require 'settings'
require 'keymappings'

require 'config.telescope'
require 'config.expand-region'
require 'config.highlight-current-n'
require 'config.switch'
require 'config.comment'
require 'config.autosave'
require 'config.move'
require 'config.vacuumline'
require 'config.gitsigns'
