#!/bin/zsh
set -e
if [ -n "$TMUX" ]; then
  nvimsocket="/tmp/nvimsocket$TMUX_PANE"
  if [ -e "$nvimsocket" ]; then
    nvr --servername $nvimsocket -cc split --remote-wait $@
  else
    nvim $@
  fi
else
  nvim $@
fi
