return {
  "williamboman/mason.nvim",
  lazy = true,
  opts = {
    ensure_installed = {
      "bash-language-server",
      "black",
      "blackd-client",
      "codelldb",
      "commitlint",
      "cspell",
      "emmet-language-server",
      "eslint_d",
      "html-lsp",
      "htmlbeautifier",
      "jdtls",
      "jq",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint",
      "markdownlint-cli2",
      "marksman",
      "prettier",
      "prettierd",
      "prisma-language-server",
      "ruby-lsp",
      "rust-analyzer",
      "shfmt",
      "solargraph",
      "sql-formatter",
      "sqlfluff",
      "sqlfmt",
      "stylua",
      "tailwindcss-language-server",
      "taplo",
      "woke",
      "yaml-language-server",
    },
  },
}
