return {
  "nvim-treesitter/nvim-treesitter",
  event = "VeryLazy",
  opts = {
    ensure_installed = {
      "bash",
      "css",
      "diff",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "html",
      "http",
      "java",
      "javascript",
      "jq",
      "json",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "mermaid",
      "prisma",
      "python",
      "query",
      "regex",
      "ruby",
      "rust",
      "sql",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
    },
    rainbow = {
      enable = true,
    },
    textobjects = {
      select = {
        enable = true,
      },
      move = {
        enable = false,
      },
    },
  },
}
