# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json
# https://espanso.org/docs/

matches:
  # Emails
  - trigger: 'kte'
    replace: 'kevintraver@kevintraver.com'

  - trigger: 'kgm'
    replace: 'kevintraver@gmail.com'

  # Localhost shortcuts
  - trigger: 'lh3'
    replace: 'http://localhost:3000/'

  - trigger: 'lh4'
    replace: 'http://localhost:4111/'

  - trigger: 'lh80'
    replace: 'http://localhost:8080/'

  - trigger: 'lh81'
    replace: 'http://localhost:8081/'

  - trigger: 'lh8000'
    replace: 'http://localhost:8000/'

  # Dynamic localhost by port, e.g., 5173lh -> http://localhost:5173
  - regex: '(?P<port>\d{1,5})lh'
    replace: 'http://localhost:{{port}}'

  # Emoji
  - trigger: 'lol'
    replace: '😆'
  - trigger: 'LOL'
    replace: '😂'
  - trigger: 'rofl'
    replace: '🤣'
  - trigger: ':mf'
    replace: '🫠'
  - trigger: ':angry'
    replace: '😡'
  - trigger: ':wink'
    replace: '😉'
  - trigger: ':uf'
    replace: '🙃'
  - trigger: ':tu'
    replace: '👍'
  - trigger: ':td'
    replace: '👎'
  - trigger: ':-'
    replace: '😬'
  - trigger: ':oo'
    replace: '😮'
  - trigger: ':he'
    replace: '🤯'
  - trigger: ':party:'
    replace: '🎉'
  - trigger: ':partyface:'
    replace: '🥳'
  - trigger: ':zzz'
    replace: '😴'

  # Dates / Times
  - trigger: ':ddate'
    replace: '{{date}}'
    vars:
      - name: date
        type: date
        params:
          format: '%m-%d-%Y'

  - trigger: ':ttime'
    replace: '{{time}}'
    vars:
      - name: time
        type: date
        params:
          format: '%H:%M:%S'

  - trigger: ':dtime'
    replace: '{{datetime}}'
    vars:
      - name: datetime
        type: date
        params:
          format: '%m-%d-%Y %H:%M:%S'

  - trigger: ':dateiso'
    replace: '{{dateiso}}'
    vars:
      - name: dateiso
        type: date
        params:
          format: '%Y-%m-%d'

  - trigger: ':ts'
    replace: '{{timestamp}}'
    vars:
      - name: timestamp
        type: date
        params:
          format: '%Y-%m-%d %H:%M'

  - trigger: ':epoch'
    replace: '{{epoch}}'
    vars:
      - name: epoch
        type: shell
        params:
          cmd: 'date +%s'

  - trigger: ':unix'
    replace: '{{epoch}}'
    vars:
      - name: epoch
        type: shell
        params:
          cmd: 'date +%s'

  # Utilities / System
  - trigger: ':uuid'
    replace: '{{uuid}}'
    vars:
      - name: uuid
        type: shell
        params:
          cmd: 'uuidgen'

  - trigger: ':ip:'
    replace: '{{output}}'
    vars:
      - name: output
        type: shell
        params:
          cmd: 'ipconfig getifaddr en0'

  # Git
  - trigger: ':aic'
    replace: 'Commit all the current changes with detailed messages using git commit conventional syntax'

  - trigger: ':aib'
    replace: 'Review all the uncommitted changes. Then create a new branch with a name based on theses features. Then commit the changes with detailed messages using git commit conventional syntax'
