# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json
# https://espanso.org/docs/

matches:
  - trigger: 'kte'
    replace: 'kevintraver@kevintraver.com'

  - trigger: 'lh3'
    replace: 'http://localhost:3000/'
  - trigger: 'lh4'
    replace: 'http://localhost:4000/'
  - trigger: 'lh8'
    replace: 'http://localhost:8000/'

  - trigger: 'lol'
    replace: "\U0001F606"
  - trigger: 'LOL'
    replace: "\U0001F602"
  - trigger: 'rofl'
    replace: "\U0001F923"
  - trigger: ':mf'
    replace: "\U0001FAE0"
  - trigger: ':uf'
    replace: "\U0001F643"
  - trigger: ':tu'
    replace: "\U0001F44D"
