# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json
# https://espanso.org/docs/

matches:
  - trigger: 'kte'
    replace: 'kevintraver@kevintraver.com'

  - trigger: 'lh3'
    replace: 'http://localhost:3000/'
  - trigger: 'lh4'
    replace: 'http://localhost:4000/'
  - trigger: 'lh8'
    replace: 'http://localhost:8000/'
