# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json
# https://espanso.org/docs/

matches:
  - trigger: 'kte'
    replace: 'kevintraver@kevintraver.com'

  - trigger: 'lh3'
    replace: 'http://localhost:3000/'
  - trigger: 'lh4'
    replace: 'http://localhost:4111/'
  - trigger: 'lh80'
    replace: 'http://localhost:8080/'
  - trigger: 'lh81'
    replace: 'http://localhost:8081/'
  - trigger: 'lh8000'
    replace: 'http://localhost:8000/'

  # Dynamic localhost by port, e.g., 5173lh -> http://localhost:5173
  - regex: '(?P<port>\\d{1,5})lh'
    replace: 'http://localhost:{{port}}'

  - trigger: 'lol'
    replace: '😆'
  - trigger: 'LOL'
    replace: '😂'
  - trigger: 'rofl'
    replace: '🤣'
  - trigger: ':mf'
    replace: '🫠'
  - trigger: ':angry'
    replace: '😡'
  - trigger: ':wink'
    replace: '😉'
  - trigger: ':uf'
    replace: '🙃'
  - trigger: ':tu'
    replace: '👍'
  - trigger: ':td'
    replace: '👎'
  - trigger: ':-'
    replace: '😬'
  - trigger: ':oo'
    replace: '😮'
  - trigger: ':he'
    replace: '🤯'
  - trigger: ':party:'
    replace: '🎉'
  - trigger: ':partyface:'
    replace: '🥳'
  - trigger: ':zzz'
    replace: '😴'

  - trigger: ':ip:'
    replace: '{{output}}'
    vars:
      - name: output
        type: shell
        params:
          cmd: 'ipconfig getifaddr en0'

  - trigger: 'ddate'
    replace: '{{date}}'
    vars:
      - name: date
        type: date
        params:
          format: '%m-%d-%Y'

  - trigger: 'ttime'
    replace: '{{time}}'
    vars:
      - name: time
        type: date
        params:
          format: '%H:%M:%S'

  - trigger: 'dtime'
    replace: '{{datetime}}'
    vars:
      - name: datetime
        type: date
        params:
          format: '%m-%d-%Y %H:%M:%S'
