source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"

autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

autoload -U promptinit; promptinit

zinit ice pick"async.zsh" src"pure.zsh"
zinit light sindresorhus/pure


zinit ice blockf atpull'zinit creinstall -q .'
zinit light zsh-users/zsh-completions

autoload compinit
compinit

zinit light zdharma-continuum/fast-syntax-highlighting

zinit light Aloxaf/fzf-tab
zstyle ':fzf-tab:*' fzf-bindings 'tab:accept'

zinit light babarot/enhancd
zinit light wfxr/forgit

zinit snippet OMZP::git

source ~/.zshrc.local

source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

eval "$(zoxide init zsh)"

export PAGER=page
export MANPAGER="page -t man"


if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
    alias nvim=nvr -cc split --remote-wait +'set bufhidden=wipe'
fi


if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
    export VISUAL="nvr -cc split --remote-wait +'set bufhidden=wipe'"
    export EDITOR="nvr -cc split --remote-wait +'set bufhidden=wipe'"
else
    export VISUAL="nvim"
    export EDITOR="nvim"
fi

autoload -U edit-command-line
zle -N edit-command-line
bindkey '^e' edit-command-line

eval "$(mcfly init zsh)"
eval "$(mcfly-fzf init zsh)"

export FZF_DEFAULT_OPTS="
--height=50%
--layout=reverse
--bind 'tab:accept'
"

alias l='exa -lbF --git'
alias ls='exa'
alias ll='exa -lbGF --git'
alias llm='exa -lbGd --git --sort=modified'
alias la='exa -lbhHigUmuSa --time-style=long-iso --git --color-scale'
alias lx='exa -lbhHigUmuSa@ --time-style=long-iso --git --color-scale'
alias lS='exa -1'
alias lt='exa --tree --level=2'

export DOTFILES_HOME="$HOME/.dotfiles/zsh"
source "$DOTFILES_HOME/aliases.zsh"

HISTORY_IGNORE=$(cat $DOTFILES_HOME/history_ignore_patterns.txt | tr '\n' '|')
HISTORY_IGNORE=${HISTORY_IGNORE%|}
